version: "3.9"

services:
  mysql:
    image: mysql:8
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: change-me
      MYSQL_DATABASE: housing
    ports:
      - "3306:3306"

volumes:
  mysql-data: